/**
 * One-off script: Phase 4 Location & Address Architecture — seeds
 * `neighborhoods/{neighborhoodId}` from the validated OCHA COD-AB-SYR
 * `syr_neighborhoods` extraction (see the Phase 2 data-acquisition report
 * and the Phase 3 validation report — 414 records across Damascus, Aleppo,
 * Homs, Lattakia, Tartous, Ar-Raqqa, Hama, Deir-ez-Zor, Al-Hasakeh, Dar'a,
 * Idleb, As-Sweida, and the Yarmuk special case). Every nameEn/nameAr value
 * below is copied verbatim from that extraction — nothing invented,
 * reconstructed from memory, or auto-translated — with exactly two
 * source-data handling decisions, both already reported in Phase 3:
 *
 *  1. Aleppo N0164 ("Ad-Dallain") — OCHA's own source file stores the
 *     Arabic name tripled with embedded line breaks (a confirmed data-entry
 *     artifact, verified directly in the raw XLSX sharedStrings.xml).
 *     Stored once here — "الدلالين" — per Phase 4 requirement #4.
 *  2. Yarmuk (N0109-N0111) — OCHA's own P-code hierarchy scopes these three
 *     records under a distinct adm4 locality ("Yarmuk"/اليرموك, pcode
 *     C1002), structurally parallel to Damascus city itself (pcode C1001)
 *     rather than nested inside it. Seeded under cityId "damascus_yarmuk"
 *     (see seed-syrian-cities-phase4.ts, which must run first) rather than
 *     folded into Damascus's other 97 neighbourhoods, per Phase 4
 *     requirement #5.
 *
 * enabled:false marks the four records the Phase 3 validation report
 * classified as SPECIAL_AREA/INDUSTRIAL_AREA/CAMP (a university campus, two
 * industrial zones, one refugee camp) — kept in the dataset (never
 * deleted), just excluded from the customer-facing neighbourhood picker via
 * NeighborhoodOption.enabled, same mechanism models/neighborhood.dart's own
 * doc comment describes. Every other record is enabled:true, INCLUDING the
 * Phase 3 REQUIRES_REVIEW records (ambiguous "_"/"/"-joined compound names,
 * and Dar'a's neighbourhood literally named "Quneitra") — those are real,
 * selectable places flagged for a future manual naming review, not
 * unsuitable for the picker; see the Phase 3 report's Section 2 for the
 * full reasoning per record.
 *
 * [id] is a proposed slug (`<cityId>_<normalized_english_name>`, with the
 * source P-code appended on a same-city collision) — the same scheme
 * proposed as a CANDIDATE in the Phase 2 report, now finalized as the
 * actual document id. [ochaPcode] preserves the traceability link back to
 * the exact OCHA source row.
 *
 * Requires seed-syrian-cities-phase4.ts (and the original seed-cities.ts)
 * to have already run — firestore.rules' neighborhoods/{neighborhoodId}
 * create rule requires the referenced cities/{cityId} doc to exist.
 *
 * Writes via the Admin SDK, bypassing firestore.rules — same as every
 * other seed script in this directory. Every doc id is deterministic and
 * written with `.set()`, so re-running this script is a safe, idempotent
 * overwrite.
 *
 * Usage (real project):
 *   GOOGLE_APPLICATION_CREDENTIALS="$env:APPDATA\firebase\<you>_application_default_credentials.json" \
 *   npx ts-node scripts/seed-neighborhoods.ts --yes
 *
 * Refuses to run without --yes or against an emulator env — same guards as
 * every other seed script in this directory.
 */
import * as admin from "firebase-admin";

const PROJECT_ID = "delivery-app-syria-2026";

interface NeighborhoodSeed {
  id: string;
  nameEn: string;
  nameAr: string;
  cityId: string;
  enabled: boolean;
  order: number;
  ochaPcode: string;
}

// 414 records, generated from the OCHA COD-AB-SYR
// syr_neighborhoods extraction — see this file's own doc comment above.
const NEIGHBORHOODS: NeighborhoodSeed[] = [
  { id: "damascus_al_hurriya__ish_al_werwer", nameEn: "Al Hurriya_ Ish Al Werwer", nameAr: "الحرية_ عش الورور", cityId: "damascus", enabled: true, order: 0, ochaPcode: "N0001" },
  { id: "damascus_barza_al_balad", nameEn: "Barza Al Balad", nameAr: "برزة البلد", cityId: "damascus", enabled: true, order: 1, ochaPcode: "N0002" },
  { id: "damascus_al_manara", nameEn: "Al Manara", nameAr: "المنارة", cityId: "damascus", enabled: true, order: 2, ochaPcode: "N0003" },
  { id: "damascus_tishrine", nameEn: "Tishrine", nameAr: "تشرين", cityId: "damascus", enabled: true, order: 3, ochaPcode: "N0004" },
  { id: "damascus_al_abbas", nameEn: "Al Abbas", nameAr: "العباس", cityId: "damascus", enabled: true, order: 4, ochaPcode: "N0005" },
  { id: "damascus_asad_addein", nameEn: "Asad Addein", nameAr: "أسد الدين", cityId: "damascus", enabled: true, order: 5, ochaPcode: "N0006" },
  { id: "damascus_qaboun", nameEn: "Qaboun", nameAr: "القابون", cityId: "damascus", enabled: true, order: 6, ochaPcode: "N0007" },
  { id: "damascus_masakin_barza", nameEn: "Masakin Barza", nameAr: "مساكن برزة", cityId: "damascus", enabled: true, order: 7, ochaPcode: "N0008" },
  { id: "damascus_naqshabandi", nameEn: "Naqshabandi", nameAr: "النقشبندي", cityId: "damascus", enabled: true, order: 8, ochaPcode: "N0009" },
  { id: "damascus_dummar_sharqiya", nameEn: "Dummar Sharqiya", nameAr: "دمر الشرقية", cityId: "damascus", enabled: true, order: 9, ochaPcode: "N0010" },
  { id: "damascus_al_masani", nameEn: "Al Masani'", nameAr: "المصانع", cityId: "damascus", enabled: true, order: 10, ochaPcode: "N0011" },
  { id: "damascus_al_woroud", nameEn: "Al Woroud", nameAr: "الورود", cityId: "damascus", enabled: true, order: 11, ochaPcode: "N0012" },
  { id: "damascus_ayoubiya", nameEn: "Ayoubiya", nameAr: "الأيوبية", cityId: "damascus", enabled: true, order: 12, ochaPcode: "N0013" },
  { id: "damascus_qasyoun", nameEn: "Qasyoun", nameAr: "قاسيون", cityId: "damascus", enabled: true, order: 13, ochaPcode: "N0014" },
  { id: "damascus_nuzha", nameEn: "Nuzha", nameAr: "النزهة", cityId: "damascus", enabled: true, order: 14, ochaPcode: "N0015" },
  { id: "damascus_al_fayhaa", nameEn: "Al Fayhaa", nameAr: "الفيحاء", cityId: "damascus", enabled: true, order: 15, ochaPcode: "N0016" },
  { id: "damascus_abou_jarash", nameEn: "Abou Jarash", nameAr: "أبو جرش", cityId: "damascus", enabled: true, order: 16, ochaPcode: "N0017" },
  { id: "damascus_faris_al_khouri", nameEn: "Faris Al Khouri", nameAr: "فارس الخوري", cityId: "damascus", enabled: true, order: 17, ochaPcode: "N0018" },
  { id: "damascus_sheikh_muhie_addin", nameEn: "Sheikh Muhie Addin", nameAr: "الشيخ محي الدين", cityId: "damascus", enabled: true, order: 18, ochaPcode: "N0019" },
  { id: "damascus_al_arin", nameEn: "Al Arin", nameAr: "العرين", cityId: "damascus", enabled: true, order: 19, ochaPcode: "N0020" },
  { id: "damascus_al_madaris", nameEn: "Al Madaris", nameAr: "المدارس", cityId: "damascus", enabled: true, order: 20, ochaPcode: "N0021" },
  { id: "damascus_shoura", nameEn: "Shoura", nameAr: "شورى", cityId: "damascus", enabled: true, order: 21, ochaPcode: "N0022" },
  { id: "damascus_mastaba", nameEn: "Mastaba", nameAr: "المصطبة", cityId: "damascus", enabled: true, order: 22, ochaPcode: "N0023" },
  { id: "damascus_dahiet_dummar", nameEn: "Dahiet Dummar", nameAr: "ضاحية دمر", cityId: "damascus", enabled: true, order: 23, ochaPcode: "N0024" },
  { id: "damascus_joubar_sharqi", nameEn: "Joubar Sharqi", nameAr: "جوبر الشرقي", cityId: "damascus", enabled: true, order: 24, ochaPcode: "N0025" },
  { id: "damascus_al_qusur", nameEn: "Al Qusur", nameAr: "القصور", cityId: "damascus", enabled: true, order: 25, ochaPcode: "N0026" },
  { id: "damascus_al_marabit", nameEn: "Al Marabit", nameAr: "المرابط", cityId: "damascus", enabled: true, order: 26, ochaPcode: "N0027" },
  { id: "damascus_al_mazraa", nameEn: "Al Mazra'a", nameAr: "المزرعة", cityId: "damascus", enabled: true, order: 27, ochaPcode: "N0028" },
  { id: "damascus_al_adwi", nameEn: "Al 'Adwi", nameAr: "العدوي", cityId: "damascus", enabled: true, order: 28, ochaPcode: "N0029" },
  { id: "damascus_joubar_gharbi", nameEn: "Joubar Gharbi", nameAr: "جوبر الغربي", cityId: "damascus", enabled: true, order: 29, ochaPcode: "N0030" },
  { id: "damascus_rawda", nameEn: "Rawda", nameAr: "الروضة", cityId: "damascus", enabled: true, order: 30, ochaPcode: "N0031" },
  { id: "damascus_maamouniyyeh", nameEn: "Ma'amouniyyeh", nameAr: "المأمونية", cityId: "damascus", enabled: true, order: 31, ochaPcode: "N0032" },
  { id: "damascus_shuhada", nameEn: "Shuhada", nameAr: "الشهداء", cityId: "damascus", enabled: true, order: 32, ochaPcode: "N0033" },
  { id: "damascus_al_qusa", nameEn: "Al Qusa'", nameAr: "القصاع", cityId: "damascus", enabled: true, order: 33, ochaPcode: "N0034" },
  { id: "damascus_abou_rummaneh", nameEn: "Abou Rummaneh", nameAr: "أبو رمانة", cityId: "damascus", enabled: true, order: 34, ochaPcode: "N0035" },
  { id: "damascus_al_maliki", nameEn: "Al Maliki", nameAr: "المالكي", cityId: "damascus", enabled: true, order: 35, ochaPcode: "N0036" },
  { id: "damascus_haboubi", nameEn: "Haboubi", nameAr: "الحبوبي", cityId: "damascus", enabled: true, order: 36, ochaPcode: "N0037" },
  { id: "damascus_masjid_aqsab", nameEn: "Masjid Aqsab", nameAr: "مسجد أقصاب", cityId: "damascus", enabled: true, order: 37, ochaPcode: "N0038" },
  { id: "damascus_oqaiba", nameEn: "Oqaiba", nameAr: "العقيبة", cityId: "damascus", enabled: true, order: 38, ochaPcode: "N0039" },
  { id: "damascus_saroujah", nameEn: "Saroujah", nameAr: "ساروجا", cityId: "damascus", enabled: true, order: 39, ochaPcode: "N0040" },
  { id: "damascus_amara_baraniyyeh", nameEn: "Amara Baraniyyeh", nameAr: "العمارة البرانية", cityId: "damascus", enabled: true, order: 40, ochaPcode: "N0041" },
  { id: "damascus_joura", nameEn: "Joura", nameAr: "الجورة", cityId: "damascus", enabled: true, order: 41, ochaPcode: "N0042" },
  { id: "damascus_amara_jowaniyyeh", nameEn: "Amara Jowaniyyeh", nameAr: "العمارة الجوانية", cityId: "damascus", enabled: true, order: 42, ochaPcode: "N0043" },
  { id: "damascus_dummar_gharbiya", nameEn: "Dummar Gharbiya", nameAr: "دمر الغربية", cityId: "damascus", enabled: true, order: 43, ochaPcode: "N0044" },
  { id: "damascus_hameidiyyeh", nameEn: "Hameidiyyeh", nameAr: "الحميدية", cityId: "damascus", enabled: true, order: 44, ochaPcode: "N0045" },
  { id: "damascus_hijaz", nameEn: "Hijaz", nameAr: "الحجاز", cityId: "damascus", enabled: true, order: 45, ochaPcode: "N0046" },
  { id: "damascus_rabwa", nameEn: "Rabwa", nameAr: "الربوة", cityId: "damascus", enabled: true, order: 46, ochaPcode: "N0047" },
  { id: "damascus_al_qeimariyyeh", nameEn: "Al Qeimariyyeh", nameAr: "القيمرية", cityId: "damascus", enabled: true, order: 47, ochaPcode: "N0048" },
  { id: "damascus_bab_touma", nameEn: "Bab Touma", nameAr: "باب توما", cityId: "damascus", enabled: true, order: 48, ochaPcode: "N0049" },
  { id: "damascus_hariqa", nameEn: "Hariqa", nameAr: "الحريقة", cityId: "damascus", enabled: true, order: 49, ochaPcode: "N0050" },
  { id: "damascus_al_istiqlal", nameEn: "Al Istiqlal", nameAr: "الاستقلال", cityId: "damascus", enabled: true, order: 50, ochaPcode: "N0051" },
  { id: "damascus_al_qanawat", nameEn: "Al Qanawat", nameAr: "القنوات", cityId: "damascus", enabled: true, order: 51, ochaPcode: "N0052" },
  { id: "damascus_mazzeh_86", nameEn: "Mazzeh 86", nameAr: "مزة 86", cityId: "damascus", enabled: true, order: 52, ochaPcode: "N0053" },
  { id: "damascus_shaghour_jowani", nameEn: "Shaghour Jowani", nameAr: "شاغور جواني", cityId: "damascus", enabled: true, order: 53, ochaPcode: "N0054" },
  { id: "damascus_maazanet_ash_shahm", nameEn: "Ma'azanet Ash Shahm", nameAr: "مأذنة الشحم", cityId: "damascus", enabled: true, order: 54, ochaPcode: "N0055" },
  { id: "damascus_mazzeh_al_qadimeh", nameEn: "Mazzeh Al Qadimeh", nameAr: "المزة القديمة", cityId: "damascus", enabled: true, order: 55, ochaPcode: "N0056" },
  { id: "damascus_amin", nameEn: "Amin", nameAr: "الأمين", cityId: "damascus", enabled: true, order: 56, ochaPcode: "N0057" },
  { id: "damascus_baramkeh", nameEn: "Baramkeh", nameAr: "البرامكة", cityId: "damascus", enabled: true, order: 57, ochaPcode: "N0058" },
  { id: "damascus_bab_sreijeh", nameEn: "Bab Sreijeh", nameAr: "باب سريجة", cityId: "damascus", enabled: true, order: 58, ochaPcode: "N0059" },
  { id: "damascus_bab_al_jabiyeh", nameEn: "Bab Al Jabiyeh", nameAr: "باب الجابية", cityId: "damascus", enabled: true, order: 59, ochaPcode: "N0060" },
  { id: "damascus_bab_sharqi", nameEn: "Bab Sharqi", nameAr: "باب شرقي", cityId: "damascus", enabled: true, order: 60, ochaPcode: "N0061" },
  { id: "damascus_ansari", nameEn: "Ansari", nameAr: "الأنصاري", cityId: "damascus", enabled: true, order: 61, ochaPcode: "N0062" },
  { id: "damascus_shaghour_barani", nameEn: "Shaghour Barani", nameAr: "شاغور براني", cityId: "damascus", enabled: true, order: 62, ochaPcode: "N0063" },
  { id: "damascus_mazzej_jabal", nameEn: "Mazzej Jabal", nameAr: "مزة جبل", cityId: "damascus", enabled: true, order: 63, ochaPcode: "N0064" },
  { id: "damascus_qabr_atikah", nameEn: "Qabr Atikah", nameAr: "قبر عاتكة", cityId: "damascus", enabled: true, order: 64, ochaPcode: "N0065" },
  { id: "damascus_suweiqa", nameEn: "Suweiqa", nameAr: "السويقة", cityId: "damascus", enabled: true, order: 65, ochaPcode: "N0066" },
  { id: "damascus_ibn_asaker", nameEn: "Ibn Asaker", nameAr: "ابن عساكر", cityId: "damascus", enabled: true, order: 66, ochaPcode: "N0067" },
  { id: "damascus_nidal", nameEn: "Nidal", nameAr: "النضال", cityId: "damascus", enabled: true, order: 67, ochaPcode: "N0068" },
  { id: "damascus_al_moujtahed", nameEn: "Al Moujtahed", nameAr: "المجتهد", cityId: "damascus", enabled: true, order: 68, ochaPcode: "N0069" },
  { id: "damascus_kafr_souseh_al_balad", nameEn: "Kafr Souseh Al Balad", nameAr: "كفر سوسة البلد", cityId: "damascus", enabled: true, order: 69, ochaPcode: "N0070" },
  { id: "damascus_jalaa", nameEn: "Jalaa", nameAr: "الجلاء", cityId: "damascus", enabled: true, order: 70, ochaPcode: "N0071" },
  { id: "damascus_al_ikhlas", nameEn: "Al Ikhlas", nameAr: "الإخلاص", cityId: "damascus", enabled: true, order: 71, ochaPcode: "N0072" },
  { id: "damascus_mazzeh_basatin", nameEn: "Mazzeh Basatin", nameAr: "مزة بساتين", cityId: "damascus", enabled: true, order: 72, ochaPcode: "N0073" },
  { id: "damascus_wihdeh", nameEn: "Wihdeh", nameAr: "الوحدة", cityId: "damascus", enabled: true, order: 73, ochaPcode: "N0074" },
  { id: "damascus_bilal", nameEn: "Bilal", nameAr: "بلال", cityId: "damascus", enabled: true, order: 74, ochaPcode: "N0075" },
  { id: "damascus_fealat_gharbiyeh", nameEn: "Fealat Gharbiyeh", nameAr: "فيلات غربية", cityId: "damascus", enabled: true, order: 75, ochaPcode: "N0076" },
  { id: "damascus_al_waha", nameEn: "Al Waha", nameAr: "الواحة", cityId: "damascus", enabled: true, order: 76, ochaPcode: "N0077" },
  { id: "damascus_midan_wastani", nameEn: "Midan Wastani", nameAr: "ميدان وسطاني", cityId: "damascus", enabled: true, order: 77, ochaPcode: "N0078" },
  { id: "damascus_rawdet_al_midan", nameEn: "Rawdet Al Midan", nameAr: "روضة الميدان", cityId: "damascus", enabled: true, order: 78, ochaPcode: "N0079" },
  { id: "damascus_zahreh", nameEn: "Zahreh", nameAr: "الزاهرة", cityId: "damascus", enabled: true, order: 79, ochaPcode: "N0080" },
  { id: "damascus_haqleh", nameEn: "Haqleh", nameAr: "الحقلة", cityId: "damascus", enabled: true, order: 80, ochaPcode: "N0081" },
  { id: "damascus_bab_maser", nameEn: "Bab Maser", nameAr: "باب مصر", cityId: "damascus", enabled: true, order: 81, ochaPcode: "N0082" },
  { id: "damascus_zohour", nameEn: "Zohour", nameAr: "الزهور", cityId: "damascus", enabled: true, order: 82, ochaPcode: "N0083" },
  { id: "damascus_daqaq", nameEn: "Daqaq", nameAr: "الدقاق", cityId: "damascus", enabled: true, order: 83, ochaPcode: "N0084" },
  { id: "damascus_sayyida_aisha", nameEn: "Sayyida Aisha", nameAr: "السيدة عائشة", cityId: "damascus", enabled: true, order: 84, ochaPcode: "N0085" },
  { id: "damascus_fealat_sharqiyeh", nameEn: "Fealat Sharqiyeh", nameAr: "فيلات شرقية", cityId: "damascus", enabled: true, order: 85, ochaPcode: "N0086" },
  { id: "damascus_fardos", nameEn: "Fardos", nameAr: "الفردوس", cityId: "damascus", enabled: true, order: 86, ochaPcode: "N0087" },
  { id: "damascus_soumariyyeh", nameEn: "Soumariyyeh", nameAr: "السومرية", cityId: "damascus", enabled: true, order: 87, ochaPcode: "N0088" },
  { id: "damascus_qaa", nameEn: "Qa'a", nameAr: "القاعة", cityId: "damascus", enabled: true, order: 88, ochaPcode: "N0089" },
  { id: "damascus_lwan", nameEn: "Lwan", nameAr: "اللوان", cityId: "damascus", enabled: true, order: 89, ochaPcode: "N0090" },
  { id: "damascus_dahadeel", nameEn: "Dahadeel", nameAr: "الدحاديل", cityId: "damascus", enabled: true, order: 90, ochaPcode: "N0091" },
  { id: "damascus_tadamon", nameEn: "Tadamon", nameAr: "التضامن", cityId: "damascus", enabled: true, order: 91, ochaPcode: "N0092" },
  { id: "damascus_jouret_shreibati", nameEn: "Jouret Shreibati", nameAr: "جورة الشريباتي", cityId: "damascus", enabled: true, order: 92, ochaPcode: "N0093" },
  { id: "damascus_al_qadam", nameEn: "Al Qadam", nameAr: "القدم", cityId: "damascus", enabled: true, order: 93, ochaPcode: "N0094" },
  { id: "damascus_al_mustafa", nameEn: "Al Mustafa", nameAr: "المصطفى", cityId: "damascus", enabled: true, order: 94, ochaPcode: "N0095" },
  { id: "damascus_qadam_sharqi", nameEn: "Qadam Sharqi", nameAr: "القدم الشرقي", cityId: "damascus", enabled: true, order: 95, ochaPcode: "N0096" },
  { id: "damascus_al_assali", nameEn: "Al Assali", nameAr: "العسالي", cityId: "damascus", enabled: true, order: 96, ochaPcode: "N0097" },
  { id: "aleppo_youth_housing", nameEn: "Youth Housing", nameAr: "السكن الشبابي", cityId: "aleppo", enabled: true, order: 0, ochaPcode: "N0119" },
  { id: "aleppo_ayn_at_tal", nameEn: "Ayn At-Tal", nameAr: "عين التل", cityId: "aleppo", enabled: true, order: 1, ochaPcode: "N0120" },
  { id: "aleppo_alleramoon", nameEn: "Alleramoon", nameAr: "الليرمون", cityId: "aleppo", enabled: true, order: 2, ochaPcode: "N0121" },
  { id: "aleppo_haydariyeh", nameEn: "Haydariyeh", nameAr: "حيدرية", cityId: "aleppo", enabled: true, order: 3, ochaPcode: "N0122" },
  { id: "aleppo_ash_sheikh_maqsoud", nameEn: "Ash-Sheikh Maqsoud", nameAr: "الشيخ مقصود", cityId: "aleppo", enabled: true, order: 4, ochaPcode: "N0123" },
  { id: "aleppo_rasafeh", nameEn: "Rasafeh", nameAr: "رصافة", cityId: "aleppo", enabled: true, order: 5, ochaPcode: "N0124" },
  { id: "aleppo_baaiedin", nameEn: "Ba'aiedin", nameAr: "بعيدين", cityId: "aleppo", enabled: true, order: 6, ochaPcode: "N0125" },
  { id: "aleppo_trab_al_hellok", nameEn: "Trab Al-Hellok", nameAr: "تراب الحيلوك", cityId: "aleppo", enabled: true, order: 7, ochaPcode: "N0126" },
  { id: "aleppo_khaldiyeh", nameEn: "Khaldiyeh", nameAr: "خالدية", cityId: "aleppo", enabled: true, order: 8, ochaPcode: "N0127" },
  { id: "aleppo_ashrafiyeh", nameEn: "Ashrafiyeh", nameAr: "الأشرفية", cityId: "aleppo", enabled: true, order: 9, ochaPcode: "N0128" },
  { id: "aleppo_hanano", nameEn: "Hanano", nameAr: "هنانو", cityId: "aleppo", enabled: true, order: 10, ochaPcode: "N0129" },
  { id: "aleppo_bostan_bash", nameEn: "Bostan Bash", nameAr: "بستان الباشا", cityId: "aleppo", enabled: true, order: 11, ochaPcode: "N0130" },
  { id: "aleppo_nile_street", nameEn: "Nile Street", nameAr: "شارع النيل", cityId: "aleppo", enabled: true, order: 12, ochaPcode: "N0131" },
  { id: "aleppo_sheikh_fares", nameEn: "Sheikh Fares", nameAr: "شيخ فارس", cityId: "aleppo", enabled: true, order: 13, ochaPcode: "N0132" },
  { id: "aleppo_andalus", nameEn: "Andalus", nameAr: "الأندلس", cityId: "aleppo", enabled: true, order: 14, ochaPcode: "N0133" },
  { id: "aleppo_sheikh_kheder", nameEn: "Sheikh Kheder", nameAr: "شيخ خضر", cityId: "aleppo", enabled: true, order: 15, ochaPcode: "N0134" },
  { id: "aleppo_az_zahraa", nameEn: "Az-Zahraa", nameAr: "الزهراء", cityId: "aleppo", enabled: true, order: 16, ochaPcode: "N0135" },
  { id: "aleppo_tareq_ben_ziad", nameEn: "Tareq Ben Ziad", nameAr: "طارق بن زياد", cityId: "aleppo", enabled: true, order: 17, ochaPcode: "N0136" },
  { id: "aleppo_zuhour", nameEn: "Zuhour", nameAr: "الزهور", cityId: "aleppo", enabled: true, order: 18, ochaPcode: "N0137" },
  { id: "aleppo_midan", nameEn: "Midan", nameAr: "الميدان", cityId: "aleppo", enabled: true, order: 19, ochaPcode: "N0138" },
  { id: "aleppo_al_sakhour", nameEn: "Al-Sakhour", nameAr: "الصاخور", cityId: "aleppo", enabled: true, order: 20, ochaPcode: "N0139" },
  { id: "aleppo_suleimaniyeh", nameEn: "Suleimaniyeh", nameAr: "السليمانية", cityId: "aleppo", enabled: true, order: 21, ochaPcode: "N0140" },
  { id: "aleppo_syriac_quarter", nameEn: "Syriac Quarter", nameAr: "حي السريان", cityId: "aleppo", enabled: true, order: 22, ochaPcode: "N0141" },
  { id: "aleppo_sulieman_al_halbi", nameEn: "Sulieman Al-Halbi", nameAr: "سليمان الحلبي", cityId: "aleppo", enabled: true, order: 23, ochaPcode: "N0142" },
  { id: "aleppo_as_sabil", nameEn: "As-Sabil", nameAr: "السبيل", cityId: "aleppo", enabled: true, order: 24, ochaPcode: "N0143" },
  { id: "aleppo_ash_shahbaa", nameEn: "Ash-Shahba'a", nameAr: "الشهباء", cityId: "aleppo", enabled: true, order: 25, ochaPcode: "N0144" },
  { id: "aleppo_jabriyeh", nameEn: "Jabriyeh", nameAr: "جابرية", cityId: "aleppo", enabled: true, order: 26, ochaPcode: "N0145" },
  { id: "aleppo_jabal_badro", nameEn: "Jabal Badro", nameAr: "جبل بدرو", cityId: "aleppo", enabled: true, order: 27, ochaPcode: "N0146" },
  { id: "aleppo_sheikh_abu_bakr", nameEn: "Sheikh Abu Bakr", nameAr: "شيخ أبو بكر", cityId: "aleppo", enabled: true, order: 28, ochaPcode: "N0147" },
  { id: "aleppo_al_aarqoub", nameEn: "Al-A'arqoub", nameAr: "العرقوب", cityId: "aleppo", enabled: true, order: 29, ochaPcode: "N0148" },
  { id: "aleppo_ourubah", nameEn: "Ourubah", nameAr: "عروبة", cityId: "aleppo", enabled: true, order: 30, ochaPcode: "N0149" },
  { id: "aleppo_hameidiyyeh", nameEn: "Hameidiyyeh", nameAr: "الحميدية", cityId: "aleppo", enabled: true, order: 31, ochaPcode: "N0150" },
  { id: "aleppo_al_mohafaza", nameEn: "Al-Mohafaza", nameAr: "المحافظة", cityId: "aleppo", enabled: true, order: 32, ochaPcode: "N0151" },
  { id: "aleppo_karm_al_jabal", nameEn: "Karm Al-Jabal", nameAr: "كرم الجبل", cityId: "aleppo", enabled: true, order: 33, ochaPcode: "N0152" },
  { id: "aleppo_university_of_aleppo", nameEn: "University of Aleppo", nameAr: "جامعة حلب", cityId: "aleppo", enabled: false, order: 34, ochaPcode: "N0153" },
  { id: "aleppo_al_hazzazeh", nameEn: "Al-Hazzazeh", nameAr: "الهزازة", cityId: "aleppo", enabled: true, order: 35, ochaPcode: "N0154" },
  { id: "aleppo_aghyol", nameEn: "Aghyol", nameAr: "أغيول", cityId: "aleppo", enabled: true, order: 36, ochaPcode: "N0155" },
  { id: "aleppo_shaaar", nameEn: "Sha'aar", nameAr: "الشعار", cityId: "aleppo", enabled: true, order: 37, ochaPcode: "N0156" },
  { id: "aleppo_helwaniyeh", nameEn: "Helwaniyeh", nameAr: "حلوانية", cityId: "aleppo", enabled: true, order: 38, ochaPcode: "N0157" },
  { id: "aleppo_almaji", nameEn: "Almaji", nameAr: "الألمه جي", cityId: "aleppo", enabled: true, order: 39, ochaPcode: "N0158" },
  { id: "aleppo_qarleq", nameEn: "Qarleq", nameAr: "قرلق", cityId: "aleppo", enabled: true, order: 40, ochaPcode: "N0159" },
  { id: "aleppo_aaziziyeh", nameEn: "A'aziziyeh", nameAr: "العزيزية", cityId: "aleppo", enabled: true, order: 41, ochaPcode: "N0160" },
  { id: "aleppo_jamiliyeh", nameEn: "Jamiliyeh", nameAr: "جميلية", cityId: "aleppo", enabled: true, order: 42, ochaPcode: "N0161" },
  { id: "aleppo_al_basel", nameEn: "Al-Basel", nameAr: "الباسل", cityId: "aleppo", enabled: true, order: 43, ochaPcode: "N0162" },
  { id: "aleppo_beit_meheb_jdeydeh", nameEn: "Beit Meheb / Jdeydeh", nameAr: "بيت محب/ جديدة", cityId: "aleppo", enabled: true, order: 44, ochaPcode: "N0163" },
  { id: "aleppo_ad_dallain", nameEn: "Ad-Dallain", nameAr: "الدلالين", cityId: "aleppo", enabled: true, order: 45, ochaPcode: "N0164" },
  { id: "aleppo_qastal_mosht", nameEn: "Qastal Mosht", nameAr: "قصطل مشط", cityId: "aleppo", enabled: true, order: 46, ochaPcode: "N0165" },
  { id: "aleppo_ibn_yaaqoub", nameEn: "Ibn Ya'aqoub", nameAr: "ابن يعقوب", cityId: "aleppo", enabled: true, order: 47, ochaPcode: "N0166" },
  { id: "aleppo_tatarlar", nameEn: "Tatarlar", nameAr: "تاترلار", cityId: "aleppo", enabled: true, order: 48, ochaPcode: "N0167" },
  { id: "aleppo_jouret_awwad", nameEn: "Jouret Awwad", nameAr: "جورة عواد", cityId: "aleppo", enabled: true, order: 49, ochaPcode: "N0168" },
  { id: "aleppo_al_kawakbi", nameEn: "Al-Kawakbi", nameAr: "الكواكبي", cityId: "aleppo", enabled: true, order: 50, ochaPcode: "N0169" },
  { id: "aleppo_al_farafra", nameEn: "Al-Farafra", nameAr: "الفرافرة", cityId: "aleppo", enabled: true, order: 51, ochaPcode: "N0170" },
  { id: "aleppo_abraj", nameEn: "Abraj", nameAr: "أبراج", cityId: "aleppo", enabled: true, order: 52, ochaPcode: "N0171" },
  { id: "aleppo_ash_shuhada", nameEn: "Ash-Shuhada", nameAr: "الشهداء", cityId: "aleppo", enabled: true, order: 53, ochaPcode: "N0172" },
  { id: "aleppo_al_feid", nameEn: "Al-Feid", nameAr: "الفيض", cityId: "aleppo", enabled: true, order: 54, ochaPcode: "N0173" },
  { id: "aleppo_qadi_askar", nameEn: "Qadi Askar", nameAr: "قاضي عسكر", cityId: "aleppo", enabled: true, order: 55, ochaPcode: "N0174" },
  { id: "aleppo_al_aqabeh", nameEn: "Al-Aqabeh", nameAr: "العقبة", cityId: "aleppo", enabled: true, order: 56, ochaPcode: "N0175" },
  { id: "aleppo_al_furqan", nameEn: "Al-Furqan", nameAr: "الفرقان", cityId: "aleppo", enabled: true, order: 57, ochaPcode: "N0176" },
  { id: "aleppo_karm_al_qaterji", nameEn: "Karm Al-Qaterji", nameAr: "كرم القاطرجي", cityId: "aleppo", enabled: true, order: 58, ochaPcode: "N0177" },
  { id: "aleppo_bayada", nameEn: "Bayada", nameAr: "بياضة", cityId: "aleppo", enabled: true, order: 59, ochaPcode: "N0178" },
  { id: "aleppo_dahert_awwad", nameEn: "Dahert Awwad", nameAr: "ضهرة عواد", cityId: "aleppo", enabled: true, order: 60, ochaPcode: "N0179" },
  { id: "aleppo_sajilikhan", nameEn: "Sajilikhan", nameAr: "صاجيليخان", cityId: "aleppo", enabled: true, order: 61, ochaPcode: "N0180" },
  { id: "aleppo_al_ghazali", nameEn: "Al-Ghazali", nameAr: "الغزالي", cityId: "aleppo", enabled: true, order: 62, ochaPcode: "N0181" },
  { id: "aleppo_masharqa", nameEn: "Masharqa", nameAr: "مشارقة", cityId: "aleppo", enabled: true, order: 63, ochaPcode: "N0182" },
  { id: "aleppo_maasaraniyeh_youth_housing", nameEn: "Ma'asaraniyeh Youth Housing", nameAr: "سكن شبابي معصرانيه", cityId: "aleppo", enabled: true, order: 64, ochaPcode: "N0183" },
  { id: "aleppo_new_aleppo", nameEn: "New Aleppo", nameAr: "حلب الجديدة", cityId: "aleppo", enabled: true, order: 65, ochaPcode: "N0184" },
  { id: "aleppo_al_madina_old_souq", nameEn: "Al-Madina Old Souq", nameAr: "سوق المدينة القديم", cityId: "aleppo", enabled: true, order: 66, ochaPcode: "N0185" },
  { id: "aleppo_oghlu_bek", nameEn: "Oghlu Bek", nameAr: "أوغلو بك", cityId: "aleppo", enabled: true, order: 67, ochaPcode: "N0186" },
  { id: "aleppo_karm_al_jazmati", nameEn: "Karm Al-Jazmati", nameAr: "كرم الجزماتي", cityId: "aleppo", enabled: true, order: 68, ochaPcode: "N0187" },
  { id: "aleppo_ad_dudu", nameEn: "Ad-Dudu", nameAr: "الضوضو", cityId: "aleppo", enabled: true, order: 69, ochaPcode: "N0188" },
  { id: "aleppo_al_jalloum", nameEn: "Al-Jalloum", nameAr: "الجلوم", cityId: "aleppo", enabled: true, order: 70, ochaPcode: "N0189" },
  { id: "aleppo_al_aajam", nameEn: "Al-A'ajam", nameAr: "العجم", cityId: "aleppo", enabled: true, order: 71, ochaPcode: "N0190" },
  { id: "aleppo_al_ballat", nameEn: "Al-Ballat", nameAr: "البلاط", cityId: "aleppo", enabled: true, order: 72, ochaPcode: "N0191" },
  { id: "aleppo_altunbogha", nameEn: "Altunbogha", nameAr: "التونبوغا", cityId: "aleppo", enabled: true, order: 73, ochaPcode: "N0192" },
  { id: "aleppo_bustan_az_zahra", nameEn: "Bustan Az-Zahra", nameAr: "بستان الزهرة", cityId: "aleppo", enabled: true, order: 74, ochaPcode: "N0193" },
  { id: "aleppo_karm_myassar", nameEn: "Karm Myassar", nameAr: "كرم ميسر", cityId: "aleppo", enabled: true, order: 75, ochaPcode: "N0194" },
  { id: "aleppo_al_ansari", nameEn: "Al-Ansari", nameAr: "الأنصاري", cityId: "aleppo", enabled: true, order: 76, ochaPcode: "N0195" },
  { id: "aleppo_karm_homed", nameEn: "Karm Homed", nameAr: "كرم حومد", cityId: "aleppo", enabled: true, order: 77, ochaPcode: "N0196" },
  { id: "aleppo_kallaseh", nameEn: "Kallaseh", nameAr: "كلاسة", cityId: "aleppo", enabled: true, order: 78, ochaPcode: "N0197" },
  { id: "aleppo_qaalet_al_sharif", nameEn: "Qa'alet Al-Sharif", nameAr: "قلعة الشريف", cityId: "aleppo", enabled: true, order: 79, ochaPcode: "N0198" },
  { id: "aleppo_sahet_bizzeh", nameEn: "Sahet Bizzeh", nameAr: "ساحة بزة", cityId: "aleppo", enabled: true, order: 80, ochaPcode: "N0199" },
  { id: "aleppo_bab_qinnesrine", nameEn: "Bab Qinnesrine", nameAr: "باب قنيصرين", cityId: "aleppo", enabled: true, order: 81, ochaPcode: "N0200" },
  { id: "aleppo_al_asileh", nameEn: "Al-Asileh", nameAr: "الأصيلة", cityId: "aleppo", enabled: true, order: 82, ochaPcode: "N0201" },
  { id: "aleppo_al_azamiyeh", nameEn: "Al-A'zamiyeh", nameAr: "الأعظمية", cityId: "aleppo", enabled: true, order: 83, ochaPcode: "N0202" },
  { id: "aleppo_sayf_ad_dauleh", nameEn: "Sayf Ad-Dauleh", nameAr: "سيف الدولة", cityId: "aleppo", enabled: true, order: 84, ochaPcode: "N0203" },
  { id: "aleppo_bustan_al_qaser", nameEn: "Bustan Al-Qaser", nameAr: "بستان القصر", cityId: "aleppo", enabled: true, order: 85, ochaPcode: "N0204" },
  { id: "aleppo_muhamad_bek", nameEn: "Muhamad Bek", nameAr: "محمد بك", cityId: "aleppo", enabled: true, order: 86, ochaPcode: "N0205" },
  { id: "aleppo_industrial_area_in_jibreen", nameEn: "Industrial Area in Jibreen", nameAr: "منطقة صناعية جبرين", cityId: "aleppo", enabled: false, order: 87, ochaPcode: "N0206" },
  { id: "aleppo_bab_al_maqam", nameEn: "Bab Al-Maqam", nameAr: "باب المقام", cityId: "aleppo", enabled: true, order: 88, ochaPcode: "N0207" },
  { id: "aleppo_az_ziebdiyeh", nameEn: "Az-Ziebdiyeh", nameAr: "الزبدية", cityId: "aleppo", enabled: true, order: 89, ochaPcode: "N0208" },
  { id: "aleppo_fardos", nameEn: "Fardos", nameAr: "فردوس", cityId: "aleppo", enabled: true, order: 90, ochaPcode: "N0209" },
  { id: "aleppo_maqar_al_anbiyaa", nameEn: "Maqar Al-Anbiya'a", nameAr: "مقر الأنبياء", cityId: "aleppo", enabled: true, order: 91, ochaPcode: "N0210" },
  { id: "aleppo_salheen", nameEn: "Salheen", nameAr: "صالحين", cityId: "aleppo", enabled: true, order: 92, ochaPcode: "N0211" },
  { id: "aleppo_jibreen", nameEn: "Jibreen", nameAr: "جبرين", cityId: "aleppo", enabled: true, order: 93, ochaPcode: "N0212" },
  { id: "aleppo_marjeh", nameEn: "Marjeh", nameAr: "مرجة", cityId: "aleppo", enabled: true, order: 94, ochaPcode: "N0213" },
  { id: "aleppo_salah_ad_deen", nameEn: "Salah Ad-Deen", nameAr: "صلاح الدين", cityId: "aleppo", enabled: true, order: 95, ochaPcode: "N0214" },
  { id: "aleppo_east_al_ansari", nameEn: "East Al-Ansari", nameAr: "الأنصاري شرقي", cityId: "aleppo", enabled: true, order: 96, ochaPcode: "N0215" },
  { id: "aleppo_hamadaniyeh", nameEn: "Hamadaniyeh", nameAr: "الحمدانية", cityId: "aleppo", enabled: true, order: 97, ochaPcode: "N0216" },
  { id: "aleppo_karm_ad_dadaa", nameEn: "Karm Ad-Da'da'a", nameAr: "كرم الدعدع", cityId: "aleppo", enabled: true, order: 98, ochaPcode: "N0217" },
  { id: "aleppo_al_ansari_mashhad", nameEn: "Al-Ansari Mashhad", nameAr: "الأنصاري مشهد", cityId: "aleppo", enabled: true, order: 99, ochaPcode: "N0218" },
  { id: "aleppo_as_sukkari", nameEn: "As-Sukkari", nameAr: "السكري", cityId: "aleppo", enabled: true, order: 100, ochaPcode: "N0219" },
  { id: "aleppo_ard_as_sabbagh", nameEn: "Ard As-Sabbagh", nameAr: "أرض الصباغ", cityId: "aleppo", enabled: true, order: 101, ochaPcode: "N0220" },
  { id: "aleppo_tishrine", nameEn: "Tishrine", nameAr: "تشرين", cityId: "aleppo", enabled: true, order: 102, ochaPcode: "N0221" },
  { id: "aleppo_al_amerriyah", nameEn: "Al-Amerriyah", nameAr: "الأميرية", cityId: "aleppo", enabled: true, order: 103, ochaPcode: "N0222" },
  { id: "aleppo_al_nayrab", nameEn: "Al-Nayrab", nameAr: "النيرب", cityId: "aleppo", enabled: true, order: 104, ochaPcode: "N0223" },
  { id: "aleppo_tal_az_zarazir", nameEn: "Tal Az-Zarazir", nameAr: "تل الزرازير", cityId: "aleppo", enabled: true, order: 105, ochaPcode: "N0224" },
  { id: "aleppo_sheikh_said", nameEn: "Sheikh Said", nameAr: "شيخ سعيد", cityId: "aleppo", enabled: true, order: 106, ochaPcode: "N0225" },
  { id: "aleppo_ar_ramouseh_indusrtial_district", nameEn: "Ar-Ramouseh Indusrtial District", nameAr: "الراموسة/ المنطقة الصناعية", cityId: "aleppo", enabled: true, order: 107, ochaPcode: "N0226" },
  { id: "aleppo_mokhayam_handarat", nameEn: "Mokhayam Handarat", nameAr: "مخيم حندرات", cityId: "aleppo", enabled: false, order: 108, ochaPcode: "N0227" },
  { id: "homs_deir_baalba_shamali", nameEn: "Deir Ba'alba Shamali", nameAr: "دير بعلبة الشمالي", cityId: "homs", enabled: true, order: 0, ochaPcode: "N0237" },
  { id: "homs_hasaweyyah", nameEn: "Hasaweyyah", nameAr: "الحصوية", cityId: "homs", enabled: true, order: 1, ochaPcode: "N0238" },
  { id: "homs_khalidiyah", nameEn: "Khalidiyah", nameAr: "خالدية", cityId: "homs", enabled: true, order: 2, ochaPcode: "N0239" },
  { id: "homs_bayada", nameEn: "Bayada", nameAr: "البياضة", cityId: "homs", enabled: true, order: 3, ochaPcode: "N0240" },
  { id: "homs_deir_baalba_janoubi", nameEn: "Deir Ba'alba Janoubi", nameAr: "دير بعلبة الجنوبي", cityId: "homs", enabled: true, order: 4, ochaPcode: "N0241" },
  { id: "homs_mimas", nameEn: "Mimas", nameAr: "الميماس", cityId: "homs", enabled: true, order: 5, ochaPcode: "N0242" },
  { id: "homs_qosour", nameEn: "Qosour", nameAr: "القصور", cityId: "homs", enabled: true, order: 6, ochaPcode: "N0243" },
  { id: "homs_jouret_ash_shayyah", nameEn: "Jouret Ash-Shayyah", nameAr: "جورة الشياح", cityId: "homs", enabled: true, order: 7, ochaPcode: "N0244" },
  { id: "homs_sabil", nameEn: "Sabil", nameAr: "السبيل", cityId: "homs", enabled: true, order: 8, ochaPcode: "N0245" },
  { id: "homs_waer", nameEn: "Wa'er", nameAr: "الوعر", cityId: "homs", enabled: true, order: 9, ochaPcode: "N0246" },
  { id: "homs_abbasiyeh_muhajreen", nameEn: "Abbasiyeh-Muhajreen", nameAr: "العباسية-المهاجرين", cityId: "homs", enabled: true, order: 10, ochaPcode: "N0247" },
  { id: "homs_karm_shamsham", nameEn: "Karm Shamsham", nameAr: "كرم شمشم", cityId: "homs", enabled: true, order: 11, ochaPcode: "N0248" },
  { id: "homs_hameidiyyeh", nameEn: "Hameidiyyeh", nameAr: "الحميدية", cityId: "homs", enabled: true, order: 12, ochaPcode: "N0249" },
  { id: "homs_ghota", nameEn: "Ghota", nameAr: "الغوطة", cityId: "homs", enabled: true, order: 13, ochaPcode: "N0250" },
  { id: "homs_boghtasiyyah", nameEn: "Boghtasiyyah", nameAr: "البغطاسية", cityId: "homs", enabled: true, order: 14, ochaPcode: "N0251" },
  { id: "homs_bab_tadmor", nameEn: "Bab Tadmor", nameAr: "باب تدمر", cityId: "homs", enabled: true, order: 15, ochaPcode: "N0252" },
  { id: "homs_zahra", nameEn: "Zahra'", nameAr: "الزهراء", cityId: "homs", enabled: true, order: 16, ochaPcode: "N0253" },
  { id: "homs_bab_houd", nameEn: "Bab Houd", nameAr: "باب هود", cityId: "homs", enabled: true, order: 17, ochaPcode: "N0254" },
  { id: "homs_bani_sbaie", nameEn: "Bani Sbaie", nameAr: "بني السباعي", cityId: "homs", enabled: true, order: 18, ochaPcode: "N0255" },
  { id: "homs_bab_ad_draib", nameEn: "Bab Ad-Draib", nameAr: "باب الدريب", cityId: "homs", enabled: true, order: 19, ochaPcode: "N0256" },
  { id: "homs_jamal_ad_dein", nameEn: "Jamal Ad-Dein", nameAr: "جمال الدين", cityId: "homs", enabled: true, order: 20, ochaPcode: "N0257" },
  { id: "homs_jeb_aj_jandali", nameEn: "Jeb Aj-Jandali", nameAr: "جب الجندلي", cityId: "homs", enabled: true, order: 21, ochaPcode: "N0258" },
  { id: "homs_mahatta", nameEn: "Mahatta", nameAr: "المحطة", cityId: "homs", enabled: true, order: 22, ochaPcode: "N0259" },
  { id: "homs_bab_as_siba", nameEn: "Bab As-Siba'", nameAr: "باب السباع", cityId: "homs", enabled: true, order: 23, ochaPcode: "N0260" },
  { id: "homs_mraijeh", nameEn: "Mraijeh", nameAr: "المريجة", cityId: "homs", enabled: true, order: 24, ochaPcode: "N0261" },
  { id: "homs_fardos", nameEn: "Fardos", nameAr: "الفردوس", cityId: "homs", enabled: true, order: 25, ochaPcode: "N0262" },
  { id: "homs_khidr", nameEn: "Khidr", nameAr: "الخضر", cityId: "homs", enabled: true, order: 26, ochaPcode: "N0263" },
  { id: "homs_karm_az_zeitoun", nameEn: "Karm Az-Zeitoun", nameAr: "كرم الزيتون", cityId: "homs", enabled: true, order: 27, ochaPcode: "N0264" },
  { id: "homs_nuzha", nameEn: "Nuzha", nameAr: "النزهة", cityId: "homs", enabled: true, order: 28, ochaPcode: "N0265" },
  { id: "homs_karm_al_loaz", nameEn: "Karm Al-Loaz", nameAr: "كرم اللوز", cityId: "homs", enabled: true, order: 29, ochaPcode: "N0266" },
  { id: "homs_ikrima", nameEn: "Ikrima", nameAr: "عكرمة", cityId: "homs", enabled: true, order: 30, ochaPcode: "N0267" },
  { id: "homs_baba_amr", nameEn: "Baba Amr", nameAr: "بابا عمرو", cityId: "homs", enabled: true, order: 31, ochaPcode: "N0268" },
  { id: "homs_arman", nameEn: "Arman", nameAr: "الأرمن", cityId: "homs", enabled: true, order: 32, ochaPcode: "N0269" },
  { id: "homs_karm_ash_shami", nameEn: "Karm Ash-Shami", nameAr: "كرم الشامي", cityId: "homs", enabled: true, order: 33, ochaPcode: "N0270" },
  { id: "homs_wadi_ath_thahab", nameEn: "Wadi Ath-Thahab", nameAr: "وادي الذهب", cityId: "homs", enabled: true, order: 34, ochaPcode: "N0271" },
  { id: "homs_daheyat_al_waleed", nameEn: "Daheyat Al-Waleed", nameAr: "ضاحية الوليد", cityId: "homs", enabled: true, order: 35, ochaPcode: "N0272" },
  { id: "latakia_al_asad", nameEn: "Al Asad", nameAr: "الأسد", cityId: "latakia", enabled: true, order: 0, ochaPcode: "N0328" },
  { id: "latakia_squbeen", nameEn: "Squbeen", nameAr: "سقوبين", cityId: "latakia", enabled: true, order: 1, ochaPcode: "N0329" },
  { id: "latakia_ogharit", nameEn: "Ogharit", nameAr: "أوغاريت", cityId: "latakia", enabled: true, order: 2, ochaPcode: "N0330" },
  { id: "latakia_basnada", nameEn: "Basnada", nameAr: "بسنادا", cityId: "latakia", enabled: true, order: 3, ochaPcode: "N0331" },
  { id: "latakia_sunjuwan", nameEn: "Sunjuwan", nameAr: "سنجوان", cityId: "latakia", enabled: true, order: 4, ochaPcode: "N0332" },
  { id: "latakia_al_thawrah", nameEn: "Al- Thawrah", nameAr: "الثورة", cityId: "latakia", enabled: true, order: 5, ochaPcode: "N0333" },
  { id: "latakia_tishrine", nameEn: "Tishrine", nameAr: "تشرين", cityId: "latakia", enabled: true, order: 6, ochaPcode: "N0334" },
  { id: "latakia_baath", nameEn: "Baath", nameAr: "البعث", cityId: "latakia", enabled: true, order: 7, ochaPcode: "N0335" },
  { id: "latakia_jomhouriyeh", nameEn: "Jomhouriyeh", nameAr: "الجمهورية", cityId: "latakia", enabled: true, order: 8, ochaPcode: "N0336" },
  { id: "latakia_7_nisan", nameEn: "7 Nisan", nameAr: "السابع من نيسان", cityId: "latakia", enabled: true, order: 9, ochaPcode: "N0337" },
  { id: "latakia_sheikh_daher", nameEn: "Sheikh Daher", nameAr: "الشيخ ضاهر", cityId: "latakia", enabled: true, order: 10, ochaPcode: "N0338" },
  { id: "latakia_oweina", nameEn: "Oweina", nameAr: "العوينة", cityId: "latakia", enabled: true, order: 11, ochaPcode: "N0339" },
  { id: "latakia_jameet_tishrine", nameEn: "Jame'et Tishrine", nameAr: "جامعة تشرين", cityId: "latakia", enabled: true, order: 12, ochaPcode: "N0340" },
  { id: "latakia_qalaa", nameEn: "Qalaa", nameAr: "القلعة", cityId: "latakia", enabled: true, order: 13, ochaPcode: "N0341" },
  { id: "latakia_quds", nameEn: "Quds", nameAr: "القدس", cityId: "latakia", enabled: true, order: 14, ochaPcode: "N0342" },
  { id: "latakia_tabiyat", nameEn: "Tabiyat", nameAr: "الطابيات", cityId: "latakia", enabled: true, order: 15, ochaPcode: "N0343" },
  { id: "latakia_sleiba", nameEn: "Sleiba", nameAr: "الصليبة", cityId: "latakia", enabled: true, order: 16, ochaPcode: "N0344" },
  { id: "tartus_al_rabieh", nameEn: "Al-Rabieh", nameAr: "الرابية", cityId: "tartus", enabled: true, order: 0, ochaPcode: "N0440" },
  { id: "tartus_al_malaab", nameEn: "Al-Malaab", nameAr: "الملعب", cityId: "tartus", enabled: true, order: 1, ochaPcode: "N0441" },
  { id: "tartus_al_mina", nameEn: "Al-Mina", nameAr: "المينة", cityId: "tartus", enabled: true, order: 2, ochaPcode: "N0442" },
  { id: "tartus_al_karamah", nameEn: "Al-Karamah", nameAr: "الكرامة", cityId: "tartus", enabled: true, order: 3, ochaPcode: "N0443" },
  { id: "tartus_al_hamrat", nameEn: "Al-Hamrat", nameAr: "الحمرات", cityId: "tartus", enabled: true, order: 4, ochaPcode: "N0444" },
  { id: "tartus_al_mahattah", nameEn: "Al-Mahattah", nameAr: "المحطة", cityId: "tartus", enabled: true, order: 5, ochaPcode: "N0445" },
  { id: "tartus_arraml", nameEn: "Arraml", nameAr: "الرمال", cityId: "tartus", enabled: true, order: 6, ochaPcode: "N0446" },
  { id: "tartus_al_ghamkah", nameEn: "Al-Ghamkah", nameAr: "الغمقة", cityId: "tartus", enabled: true, order: 7, ochaPcode: "N0447" },
  { id: "tartus_southernal_rradar", nameEn: "Southern(Al-rradar)", nameAr: "الجنوبي-الرادار", cityId: "tartus", enabled: true, order: 8, ochaPcode: "N0448" },
  { id: "raqqa_baath", nameEn: "Baath", nameAr: "البعث", cityId: "raqqa", enabled: true, order: 0, ochaPcode: "N0459" },
  { id: "raqqa_andalus", nameEn: "Andalus", nameAr: "الأندلس", cityId: "raqqa", enabled: true, order: 1, ochaPcode: "N0460" },
  { id: "raqqa_al_thawrah", nameEn: "Al- Thawrah", nameAr: "الثورة", cityId: "raqqa", enabled: true, order: 2, ochaPcode: "N0461" },
  { id: "raqqa_hurriyeh", nameEn: "Hurriyeh", nameAr: "الحرية", cityId: "raqqa", enabled: true, order: 3, ochaPcode: "N0462" },
  { id: "raqqa_wihdeh", nameEn: "Wihdeh", nameAr: "الوحدة", cityId: "raqqa", enabled: true, order: 4, ochaPcode: "N0463" },
  { id: "raqqa_tishrine", nameEn: "Tishrine", nameAr: "تشرين", cityId: "raqqa", enabled: true, order: 5, ochaPcode: "N0464" },
  { id: "raqqa_ad_dariyeh", nameEn: "Ad Dari'yeh", nameAr: "الدرعية", cityId: "raqqa", enabled: true, order: 6, ochaPcode: "N0465" },
  { id: "raqqa_hettin", nameEn: "Hettin", nameAr: "حطين", cityId: "raqqa", enabled: true, order: 7, ochaPcode: "N0466" },
  { id: "raqqa_salhiyeh", nameEn: "Salhiyeh", nameAr: "الصالحية", cityId: "raqqa", enabled: true, order: 8, ochaPcode: "N0467" },
  { id: "raqqa_nahda", nameEn: "Nahda", nameAr: "النهضة", cityId: "raqqa", enabled: true, order: 9, ochaPcode: "N0468" },
  { id: "raqqa_mansour", nameEn: "Mansour", nameAr: "المنصور", cityId: "raqqa", enabled: true, order: 10, ochaPcode: "N0469" },
  { id: "raqqa_mahdi", nameEn: "Mahdi", nameAr: "المهدي", cityId: "raqqa", enabled: true, order: 11, ochaPcode: "N0470" },
  { id: "raqqa_batani", nameEn: "Batani", nameAr: "البتاني", cityId: "raqqa", enabled: true, order: 12, ochaPcode: "N0471" },
  { id: "raqqa_amin", nameEn: "Amin", nameAr: "الأمين", cityId: "raqqa", enabled: true, order: 13, ochaPcode: "N0472" },
  { id: "raqqa_qadessiyeh", nameEn: "Qadessiyeh", nameAr: "القادسية", cityId: "raqqa", enabled: true, order: 14, ochaPcode: "N0473" },
  { id: "raqqa_tas_heeh", nameEn: "Tas-heeh", nameAr: "التصحيح", cityId: "raqqa", enabled: true, order: 15, ochaPcode: "N0474" },
  { id: "raqqa_rashidiyeh", nameEn: "Rashidiyeh", nameAr: "الرشيد", cityId: "raqqa", enabled: true, order: 16, ochaPcode: "N0475" },
  { id: "raqqa_rafqa", nameEn: "Rafqa", nameAr: "الرافقة", cityId: "raqqa", enabled: true, order: 17, ochaPcode: "N0476" },
  { id: "raqqa_ammar_ibn_yaser", nameEn: "Ammar Ibn Yaser", nameAr: "عمار بن ياسر", cityId: "raqqa", enabled: true, order: 18, ochaPcode: "N0477" },
  { id: "raqqa_maamoun", nameEn: "Ma'amoun", nameAr: "المأمون", cityId: "raqqa", enabled: true, order: 19, ochaPcode: "N0478" },
  { id: "raqqa_hisham_ibn_abd_al_malek", nameEn: "Hisham Ibn Abd Al Malek", nameAr: "هشام بن عبد الملك", cityId: "raqqa", enabled: true, order: 20, ochaPcode: "N0479" },
  { id: "raqqa_yarmuk", nameEn: "Yarmuk", nameAr: "اليرموك", cityId: "raqqa", enabled: true, order: 21, ochaPcode: "N0480" },
  { id: "raqqa_furat", nameEn: "Furat", nameAr: "الفرات", cityId: "raqqa", enabled: true, order: 22, ochaPcode: "N0481" },
  { id: "hama_dahriyeh", nameEn: "Dahriyeh", nameAr: "الضاهرية", cityId: "hama", enabled: true, order: 0, ochaPcode: "N0283" },
  { id: "hama_tishrine", nameEn: "Tishrine", nameAr: "تشرين", cityId: "hama", enabled: true, order: 1, ochaPcode: "N0284" },
  { id: "hama_sabil", nameEn: "Sabil", nameAr: "السبيل", cityId: "hama", enabled: true, order: 2, ochaPcode: "N0285" },
  { id: "hama_souq_al_ghanam", nameEn: "Souq Al-Ghanam", nameAr: "سوق الغنم", cityId: "hama", enabled: true, order: 3, ochaPcode: "N0286" },
  { id: "hama_al_fayhaa", nameEn: "Al Fayhaa", nameAr: "الفيحاء", cityId: "hama", enabled: true, order: 4, ochaPcode: "N0287" },
  { id: "hama_shahbaa", nameEn: "Shahbaa", nameAr: "الشهباء", cityId: "hama", enabled: true, order: 5, ochaPcode: "N0288" },
  { id: "hama_kazou", nameEn: "Kazou", nameAr: "كازو", cityId: "hama", enabled: true, order: 6, ochaPcode: "N0289" },
  { id: "hama_aedin", nameEn: "Aedin", nameAr: "العائدين", cityId: "hama", enabled: true, order: 7, ochaPcode: "N0290" },
  { id: "hama_granada", nameEn: "Granada", nameAr: "غرناطة", cityId: "hama", enabled: true, order: 8, ochaPcode: "N0291" },
  { id: "hama_hameidiyyeh", nameEn: "Hameidiyyeh", nameAr: "الحميدية", cityId: "hama", enabled: true, order: 9, ochaPcode: "N0292" },
  { id: "hama_jarajmeh", nameEn: "Jarajmeh", nameAr: "الجراجمة", cityId: "hama", enabled: true, order: 10, ochaPcode: "N0293" },
  { id: "hama_shamaliyeh", nameEn: "Shamaliyeh", nameAr: "الشمالية", cityId: "hama", enabled: true, order: 11, ochaPcode: "N0294" },
  { id: "hama_al_horrieh__mohafaza", nameEn: "Al- horrieh_ Mohafaza", nameAr: "الحرية_ المحافظة", cityId: "hama", enabled: true, order: 12, ochaPcode: "N0295" },
  { id: "hama_bab_al_jesr", nameEn: "Bab Al Jesr", nameAr: "باب الجسر", cityId: "hama", enabled: true, order: 13, ochaPcode: "N0296" },
  { id: "hama_baath", nameEn: "Baath", nameAr: "البعث", cityId: "hama", enabled: true, order: 14, ochaPcode: "N0297" },
  { id: "hama_zanbaqi", nameEn: "Zanbaqi", nameAr: "الزنبقي", cityId: "hama", enabled: true, order: 15, ochaPcode: "N0298" },
  { id: "hama_madina", nameEn: "Madina", nameAr: "المدينة", cityId: "hama", enabled: true, order: 16, ochaPcode: "N0299" },
  { id: "hama_al_sinaha", nameEn: "Al-Sinaha", nameAr: "الصناعة", cityId: "hama", enabled: true, order: 17, ochaPcode: "N0300" },
  { id: "hama_baroudiyeh", nameEn: "Baroudiyeh", nameAr: "البارودية", cityId: "hama", enabled: true, order: 18, ochaPcode: "N0301" },
  { id: "hama_bashoura", nameEn: "Bashoura", nameAr: "الباشورة", cityId: "hama", enabled: true, order: 19, ochaPcode: "N0302" },
  { id: "hama_bab_qebli", nameEn: "Bab Qebli", nameAr: "باب القبلي", cityId: "hama", enabled: true, order: 20, ochaPcode: "N0303" },
  { id: "hama_dabagha", nameEn: "Dabagha", nameAr: "الدباغة", cityId: "hama", enabled: true, order: 21, ochaPcode: "N0304" },
  { id: "hama_hawarneh", nameEn: "Hawarneh", nameAr: "الحوارنة", cityId: "hama", enabled: true, order: 22, ochaPcode: "N0305" },
  { id: "hama_souq_ash_shajra", nameEn: "Souq Ash Shajra", nameAr: "سوق الشجرة", cityId: "hama", enabled: true, order: 23, ochaPcode: "N0306" },
  { id: "hama_aleiliyat", nameEn: "Aleiliyat", nameAr: "العليليات", cityId: "hama", enabled: true, order: 24, ochaPcode: "N0307" },
  { id: "hama_andalus", nameEn: "Andalus", nameAr: "الأندلس", cityId: "hama", enabled: true, order: 25, ochaPcode: "N0308" },
  { id: "hama_sharia", nameEn: "Shari'a", nameAr: "الشريعة", cityId: "hama", enabled: true, order: 26, ochaPcode: "N0309" },
  { id: "hama_mahalbeh", nameEn: "Mahalbeh", nameAr: "المحالبة", cityId: "hama", enabled: true, order: 27, ochaPcode: "N0310" },
  { id: "hama_frayeh", nameEn: "Frayeh", nameAr: "الفراية", cityId: "hama", enabled: true, order: 28, ochaPcode: "N0311" },
  { id: "hama_jalaa", nameEn: "Jalaa", nameAr: "الجلاء", cityId: "hama", enabled: true, order: 29, ochaPcode: "N0312" },
  { id: "hama_sabouniyeh", nameEn: "Sabouniyeh", nameAr: "صابونية", cityId: "hama", enabled: true, order: 30, ochaPcode: "N0313" },
  { id: "hama_riyadi", nameEn: "Riyadi", nameAr: "الرياضي", cityId: "hama", enabled: true, order: 31, ochaPcode: "N0314" },
  { id: "hama_ein_al_louzeh", nameEn: "Ein Al Louzeh", nameAr: "عين اللوزة", cityId: "hama", enabled: true, order: 32, ochaPcode: "N0315" },
  { id: "hama_nasr", nameEn: "Nasr", nameAr: "النصر", cityId: "hama", enabled: true, order: 33, ochaPcode: "N0316" },
  { id: "hama_abi_al_fedaa", nameEn: "Abi Al Fedaa", nameAr: "أبي الفداء", cityId: "hama", enabled: true, order: 34, ochaPcode: "N0317" },
  { id: "deir_ezzor_al_bougailia", nameEn: "Al Bougailia", nameAr: "البغيلية", cityId: "deir_ezzor", enabled: true, order: 0, ochaPcode: "N0411" },
  { id: "deir_ezzor_al_husainia", nameEn: "Al Husainia", nameAr: "الحسينية", cityId: "deir_ezzor", enabled: true, order: 1, ochaPcode: "N0412" },
  { id: "deir_ezzor_al_thawra__al_jourah", nameEn: "Al Thawra_ Al Jourah", nameAr: "الثورة_ الجورة", cityId: "deir_ezzor", enabled: true, order: 2, ochaPcode: "N0413" },
  { id: "deir_ezzor_al_muhajireen", nameEn: "Al Muhajireen", nameAr: "المهاجرين", cityId: "deir_ezzor", enabled: true, order: 3, ochaPcode: "N0414" },
  { id: "deir_ezzor_othmaniyeh", nameEn: "Othmaniyeh", nameAr: "العثمانية", cityId: "deir_ezzor", enabled: true, order: 4, ochaPcode: "N0415" },
  { id: "deir_ezzor_al_jami_al_kabeer_wa_al_wasat", nameEn: "Al Jami' Al Kabeer wa Al Wasat", nameAr: "الجامع الكبير والوسط", cityId: "deir_ezzor", enabled: true, order: 5, ochaPcode: "N0416" },
  { id: "deir_ezzor_hatla", nameEn: "Hatla", nameAr: "حطلة", cityId: "deir_ezzor", enabled: true, order: 6, ochaPcode: "N0417" },
  { id: "deir_ezzor_rashdiyeh", nameEn: "Rashdiyeh", nameAr: "الرشدية", cityId: "deir_ezzor", enabled: true, order: 7, ochaPcode: "N0418" },
  { id: "deir_ezzor_qosour", nameEn: "Qosour", nameAr: "القصور", cityId: "deir_ezzor", enabled: true, order: 8, ochaPcode: "N0419" },
  { id: "deir_ezzor_sheikh_yasin", nameEn: "Sheikh Yasin", nameAr: "الشيخ ياسين", cityId: "deir_ezzor", enabled: true, order: 9, ochaPcode: "N0420" },
  { id: "deir_ezzor_baajein", nameEn: "Ba'ajein", nameAr: "البعاجين", cityId: "deir_ezzor", enabled: true, order: 10, ochaPcode: "N0421" },
  { id: "deir_ezzor_abu_abed", nameEn: "Abu Abed", nameAr: "أبو عابد", cityId: "deir_ezzor", enabled: true, order: 11, ochaPcode: "N0422" },
  { id: "deir_ezzor_ali_bek_wa_abd_al_aziz", nameEn: "Ali Bek wa Abd Al Aziz", nameAr: "علي بك وعبد العزيز", cityId: "deir_ezzor", enabled: true, order: 12, ochaPcode: "N0423" },
  { id: "deir_ezzor_shuhuda", nameEn: "Shuhuda", nameAr: "الشهداء", cityId: "deir_ezzor", enabled: true, order: 13, ochaPcode: "N0424" },
  { id: "deir_ezzor_hameidiyyeh", nameEn: "Hameidiyyeh", nameAr: "الحميدية", cityId: "deir_ezzor", enabled: true, order: 14, ochaPcode: "N0425" },
  { id: "deir_ezzor_hettin", nameEn: "Hettin", nameAr: "حطين", cityId: "deir_ezzor", enabled: true, order: 15, ochaPcode: "N0426" },
  { id: "deir_ezzor_tashreen__harabesh", nameEn: "Tashreen_ Harabesh", nameAr: "تشرين_ هرابش", cityId: "deir_ezzor", enabled: true, order: 16, ochaPcode: "N0427" },
  { id: "deir_ezzor_maysalun", nameEn: "Maysalun", nameAr: "ميسلون", cityId: "deir_ezzor", enabled: true, order: 17, ochaPcode: "N0428" },
  { id: "deir_ezzor_al_jafra", nameEn: "Al Jafra", nameAr: "الجفرة", cityId: "deir_ezzor", enabled: true, order: 18, ochaPcode: "N0429" },
  { id: "hasakah_msheirfeh", nameEn: "Msheirfeh", nameAr: "مشيرفة", cityId: "hasakah", enabled: true, order: 0, ochaPcode: "N0370" },
  { id: "hasakah_khashman", nameEn: "Khashman", nameAr: "خشمان", cityId: "hasakah", enabled: true, order: 1, ochaPcode: "N0371" },
  { id: "hasakah_al_mashtal", nameEn: "Al Mashtal", nameAr: "المشتل", cityId: "hasakah", enabled: true, order: 2, ochaPcode: "N0372" },
  { id: "hasakah_meishiyeh", nameEn: "M'eishiyeh", nameAr: "المعيشية", cityId: "hasakah", enabled: true, order: 3, ochaPcode: "N0373" },
  { id: "hasakah_al_talae", nameEn: "Al Tala'e'", nameAr: "الطلائع", cityId: "hasakah", enabled: true, order: 4, ochaPcode: "N0374" },
  { id: "hasakah_baytara", nameEn: "Baytara", nameAr: "البيطرة", cityId: "hasakah", enabled: true, order: 5, ochaPcode: "N0375" },
  { id: "hasakah_tal_hajar", nameEn: "Tal Hajar", nameAr: "تل حجر", cityId: "hasakah", enabled: true, order: 6, ochaPcode: "N0376" },
  { id: "hasakah_al_mufti", nameEn: "Al Mufti", nameAr: "المفتي", cityId: "hasakah", enabled: true, order: 7, ochaPcode: "N0377" },
  { id: "hasakah_qosour", nameEn: "Qosour", nameAr: "القصور", cityId: "hasakah", enabled: true, order: 8, ochaPcode: "N0378" },
  { id: "hasakah_salhiyeh", nameEn: "Salhiyeh", nameAr: "الصالحية", cityId: "hasakah", enabled: true, order: 9, ochaPcode: "N0379" },
  { id: "hasakah_al_kallasa", nameEn: "Al Kallasa", nameAr: "الكلاسة", cityId: "hasakah", enabled: true, order: 10, ochaPcode: "N0380" },
  { id: "hasakah_al_gazal", nameEn: "Al Gazal", nameAr: "الغزل", cityId: "hasakah", enabled: true, order: 11, ochaPcode: "N0381" },
  { id: "hasakah_matar_shamali", nameEn: "Matar Shamali", nameAr: "المطار الشمالي", cityId: "hasakah", enabled: true, order: 12, ochaPcode: "N0382" },
  { id: "hasakah_al_watani", nameEn: "Al Watani", nameAr: "المشفى الوطني", cityId: "hasakah", enabled: true, order: 13, ochaPcode: "N0383" },
  { id: "hasakah_abo_amsha", nameEn: "Abo Amsha", nameAr: "أبو عمشة", cityId: "hasakah", enabled: true, order: 14, ochaPcode: "N0384" },
  { id: "hasakah_al_malab_al_baladi", nameEn: "Al Mal'ab Al Baladi", nameAr: "الملعب البلدي", cityId: "hasakah", enabled: true, order: 15, ochaPcode: "N0385" },
  { id: "hasakah_al_wasati", nameEn: "Al Wasati", nameAr: "الوسطي", cityId: "hasakah", enabled: true, order: 16, ochaPcode: "N0386" },
  { id: "hasakah_al_askari", nameEn: "Al Askari", nameAr: "العسكري", cityId: "hasakah", enabled: true, order: 17, ochaPcode: "N0387" },
  { id: "hasakah_al_matar_janoubi", nameEn: "Al Matar Janoubi", nameAr: "المطار الجنوبي", cityId: "hasakah", enabled: true, order: 18, ochaPcode: "N0388" },
  { id: "hasakah_al_khabour", nameEn: "Al Khabour", nameAr: "الخابور", cityId: "hasakah", enabled: true, order: 19, ochaPcode: "N0389" },
  { id: "hasakah_al_thawra", nameEn: "Al Thawra", nameAr: "الثورة", cityId: "hasakah", enabled: true, order: 20, ochaPcode: "N0390" },
  { id: "hasakah_al_msaken", nameEn: "Al Msaken", nameAr: "المساكن", cityId: "hasakah", enabled: true, order: 21, ochaPcode: "N0391" },
  { id: "hasakah_16_tashreen", nameEn: "16 Tashreen ", nameAr: "16 تشرين", cityId: "hasakah", enabled: true, order: 22, ochaPcode: "N0392" },
  { id: "hasakah_abo_bakr", nameEn: "Abo Bakr", nameAr: "أبو بكر", cityId: "hasakah", enabled: true, order: 23, ochaPcode: "N0393" },
  { id: "hasakah_al_madina_al_riyadia", nameEn: "Al Madina Al Riyadia", nameAr: "المدينة الرياضية", cityId: "hasakah", enabled: true, order: 24, ochaPcode: "N0394" },
  { id: "hasakah_al_lailia", nameEn: "Al Lailia", nameAr: "الليلية", cityId: "hasakah", enabled: true, order: 25, ochaPcode: "N0395" },
  { id: "hasakah_al_rusafa", nameEn: "Al Rusafa", nameAr: "الرصافة", cityId: "hasakah", enabled: true, order: 26, ochaPcode: "N0396" },
  { id: "hasakah_al_takadom", nameEn: "Al Takadom", nameAr: "التقدم", cityId: "hasakah", enabled: true, order: 27, ochaPcode: "N0397" },
  { id: "hasakah_al_villat", nameEn: "Al Villat", nameAr: "الفيلات", cityId: "hasakah", enabled: true, order: 28, ochaPcode: "N0398" },
  { id: "hasakah_al_zouhour", nameEn: "Al Zouhour", nameAr: "الزهور", cityId: "hasakah", enabled: true, order: 29, ochaPcode: "N0399" },
  { id: "hasakah_industrial", nameEn: "Industrial", nameAr: "الصناعي", cityId: "hasakah", enabled: false, order: 30, ochaPcode: "N0400" },
  { id: "daraa_elshahid_basil_elasad", nameEn: "Elshahid Basil Elasad", nameAr: "الشهيد باسل الأسد", cityId: "daraa", enabled: true, order: 0, ochaPcode: "N0492" },
  { id: "daraa_tishrine", nameEn: "Tishrine", nameAr: "تشرين", cityId: "daraa", enabled: true, order: 1, ochaPcode: "N0493" },
  { id: "daraa_baath", nameEn: "Baath", nameAr: "البعث", cityId: "daraa", enabled: true, order: 2, ochaPcode: "N0494" },
  { id: "daraa_al_thawrah", nameEn: "Al- Thawrah", nameAr: "الثورة", cityId: "daraa", enabled: true, order: 3, ochaPcode: "N0495" },
  { id: "daraa_oumawiyeen", nameEn: "Oumawiyeen", nameAr: "الأمويين", cityId: "daraa", enabled: true, order: 4, ochaPcode: "N0496" },
  { id: "daraa_maysalun", nameEn: "Maysalun", nameAr: "ميسلون", cityId: "daraa", enabled: true, order: 5, ochaPcode: "N0497" },
  { id: "daraa_zahraa", nameEn: "Zahraa", nameAr: "الزهراء", cityId: "daraa", enabled: true, order: 6, ochaPcode: "N0498" },
  { id: "daraa_hettin", nameEn: "Hettin", nameAr: "حطين", cityId: "daraa", enabled: true, order: 7, ochaPcode: "N0499" },
  { id: "daraa_al_mantiqa_al_sinaiyeh", nameEn: "Al Mantiqa Al Sina'iyeh", nameAr: "المنطقة الصناعية", cityId: "daraa", enabled: true, order: 8, ochaPcode: "N0500" },
  { id: "daraa_qadessiyeh", nameEn: "Qadessiyeh", nameAr: "القادسية", cityId: "daraa", enabled: true, order: 9, ochaPcode: "N0501" },
  { id: "daraa_shuhada", nameEn: "Shuhada", nameAr: "الشهداء", cityId: "daraa", enabled: true, order: 10, ochaPcode: "N0502" },
  { id: "daraa_quneitra", nameEn: "Quneitra", nameAr: "القنيطرة", cityId: "daraa", enabled: true, order: 11, ochaPcode: "N0503" },
  { id: "daraa_ghernata", nameEn: "Ghernata", nameAr: "غرناطة", cityId: "daraa", enabled: true, order: 12, ochaPcode: "N0504" },
  { id: "daraa_karak", nameEn: "Karak", nameAr: "الكرك", cityId: "daraa", enabled: true, order: 13, ochaPcode: "N0505" },
  { id: "daraa_al_mansheyah", nameEn: "Al Mansheyah", nameAr: "المنشية", cityId: "daraa", enabled: true, order: 14, ochaPcode: "N0506" },
  { id: "daraa_alabbasiah", nameEn: "Alabbasiah", nameAr: "العباسية", cityId: "daraa", enabled: true, order: 15, ochaPcode: "N0507" },
  { id: "daraa_al_sad", nameEn: "Al_Sad", nameAr: "السد", cityId: "daraa", enabled: true, order: 16, ochaPcode: "N0508" },
  { id: "daraa_al_yarmouk", nameEn: "Al Yarmouk", nameAr: "اليرموك", cityId: "daraa", enabled: true, order: 17, ochaPcode: "N0509" },
  { id: "daraa_arbaine", nameEn: "Arbaine", nameAr: "الأربعين", cityId: "daraa", enabled: true, order: 18, ochaPcode: "N0510" },
  { id: "daraa_bahar", nameEn: "Bahar", nameAr: "البحار", cityId: "daraa", enabled: true, order: 19, ochaPcode: "N0511" },
  { id: "idlib_al_shamali", nameEn: "Al Shamali", nameAr: "الشمالي", cityId: "idlib", enabled: true, order: 0, ochaPcode: "N0355" },
  { id: "idlib_city_centre", nameEn: "City Centre", nameAr: "مركز المدينة", cityId: "idlib", enabled: true, order: 1, ochaPcode: "N0356" },
  { id: "idlib_al_gharbi", nameEn: "Al Gharbi", nameAr: "الغربي", cityId: "idlib", enabled: true, order: 2, ochaPcode: "N0357" },
  { id: "idlib_al_sharqui", nameEn: "Al Sharqui", nameAr: "الشرقي", cityId: "idlib", enabled: true, order: 3, ochaPcode: "N0358" },
  { id: "idlib_al_janoubi", nameEn: "Al Janoubi", nameAr: "الجنوبي", cityId: "idlib", enabled: true, order: 4, ochaPcode: "N0359" },
  { id: "suwayda_wihdeh", nameEn: "Wihdeh", nameAr: "الوحدة", cityId: "suwayda", enabled: true, order: 0, ochaPcode: "N0522" },
  { id: "suwayda_mazraa", nameEn: "Mazra'a", nameAr: "المزرعة", cityId: "suwayda", enabled: true, order: 1, ochaPcode: "N0523" },
  { id: "suwayda_hurriyeh", nameEn: "Hurriyeh", nameAr: "الحرية", cityId: "suwayda", enabled: true, order: 2, ochaPcode: "N0524" },
  { id: "suwayda_nahda", nameEn: "Nahda", nameAr: "النهضة", cityId: "suwayda", enabled: true, order: 3, ochaPcode: "N0525" },
  { id: "suwayda_joulan", nameEn: "Joulan", nameAr: "الجولان", cityId: "suwayda", enabled: true, order: 4, ochaPcode: "N0526" },
  { id: "suwayda_jihad", nameEn: "Jihad", nameAr: "الجهاد", cityId: "suwayda", enabled: true, order: 5, ochaPcode: "N0527" },
  { id: "suwayda_shuhada", nameEn: "Shuhada", nameAr: "الشهداء", cityId: "suwayda", enabled: true, order: 6, ochaPcode: "N0528" },
  { id: "suwayda_fursan", nameEn: "Fursan", nameAr: "الفرسان", cityId: "suwayda", enabled: true, order: 7, ochaPcode: "N0529" },
  { id: "suwayda_al_thawrah", nameEn: "Al- Thawrah", nameAr: "الثورة", cityId: "suwayda", enabled: true, order: 8, ochaPcode: "N0530" },
  { id: "suwayda_istiqlal", nameEn: "Istiqlal", nameAr: "الاستقلال", cityId: "suwayda", enabled: true, order: 9, ochaPcode: "N0531" },
  { id: "damascus_yarmuk_el_kermel", nameEn: "El Kermel", nameAr: "الكرمل", cityId: "damascus_yarmuk", enabled: true, order: 0, ochaPcode: "N0109" },
  { id: "damascus_yarmuk_hettin", nameEn: "Hettin", nameAr: "حطين", cityId: "damascus_yarmuk", enabled: true, order: 1, ochaPcode: "N0110" },
  { id: "damascus_yarmuk_el_faloujeh", nameEn: "El Faloujeh", nameAr: "الفالوجة", cityId: "damascus_yarmuk", enabled: true, order: 2, ochaPcode: "N0111" },
];

async function main() {
  if (!process.argv.includes("--yes")) {
    throw new Error(
      "Refusing to run without --yes — this writes to the LIVE delivery-app-syria-2026 project."
    );
  }
  if (process.env.FIRESTORE_EMULATOR_HOST) {
    throw new Error(
      "FIRESTORE_EMULATOR_HOST is set — this script seeds real reference data on the live " +
        "project, not emulator/demo data. Unset it before running."
    );
  }

  admin.initializeApp({ projectId: PROJECT_ID });
  const db = admin.firestore();

  for (const [index, neighborhood] of NEIGHBORHOODS.entries()) {
    await db.collection("neighborhoods").doc(neighborhood.id).set({
      nameEn: neighborhood.nameEn,
      nameAr: neighborhood.nameAr,
      cityId: neighborhood.cityId,
      enabled: neighborhood.enabled,
      order: neighborhood.order,
      ochaPcode: neighborhood.ochaPcode,
    });
    if ((index + 1) % 25 === 0 || index === NEIGHBORHOODS.length - 1) {
      console.log(`Seeded ${index + 1}/${NEIGHBORHOODS.length}`);
    }
  }
}

main()
  .then(() => process.exit(0))
  .catch((error) => {
    console.error(error);
    process.exit(1);
  });
