// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCaBAtzFjz5duGjoOFxdGdWlOefSrGhoHI',
    appId: '1:637107525940:web:69e898d8103a8c8e58ad61',
    messagingSenderId: '637107525940',
    projectId: 'delivery-app-syria-2026',
    authDomain: 'delivery-app-syria-2026.firebaseapp.com',
    storageBucket: 'delivery-app-syria-2026.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAO0P8zt9jbWg47aGZJEFQk-v5No6CSXX8',
    appId: '1:637107525940:android:58654e30de67123d58ad61',
    messagingSenderId: '637107525940',
    projectId: 'delivery-app-syria-2026',
    storageBucket: 'delivery-app-syria-2026.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAZTapOOZ8lQnoT2dUisv6DJ63GaSMMULs',
    appId: '1:637107525940:ios:79b030df1fb9d36458ad61',
    messagingSenderId: '637107525940',
    projectId: 'delivery-app-syria-2026',
    storageBucket: 'delivery-app-syria-2026.firebasestorage.app',
    iosBundleId: 'com.deliveryapp.deliveryApp',
  );
}
