// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBFTmB9a-JKR-6r9PmKV_uQLgS3MD6IOOs',
    appId: '1:837061684401:web:5cab1127cea89d910a0690',
    messagingSenderId: '837061684401',
    projectId: 'orient-food-9c1e0',
    authDomain: 'orient-food-9c1e0.firebaseapp.com',
    storageBucket: 'orient-food-9c1e0.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC_yk-KNIVKIIlgTYdRZnKrbjouddzWvR8',
    appId: '1:837061684401:android:ca167e9674055c6f0a0690',
    messagingSenderId: '837061684401',
    projectId: 'orient-food-9c1e0',
    storageBucket: 'orient-food-9c1e0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBAaRWb3JU6rp7YJwsZzKUDF2TCOuma-Yo',
    appId: '1:837061684401:ios:6d2079aa341594fb0a0690',
    messagingSenderId: '837061684401',
    projectId: 'orient-food-9c1e0',
    storageBucket: 'orient-food-9c1e0.firebasestorage.app',
    iosBundleId: 'com.deliveryapp.deliveryApp',
  );
}
